name: Nielsen Web Scrape Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pandas sqlalchemy psycopg2-binary papermill requests firecrawl

    - name: Run Nielsen Web Scrape Notebook
      run: |
        papermill Notebooks/Web_Scrape_Extract_Load_Raw.ipynb Notebooks/Web_Scrape_Extract_Load_Raw_output.ipynb