name: TVmaze API Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8am UTC

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install pandas sqlalchemy psycopg2-binary papermill requests

    - name: Run TVmaze API Notebook
      run: |
        papermill Notebooks/API_Extract_Load_Raw.ipynb Notebooks/API_Extract_Load_Raw_output.ipynb
